### ISSUE TITLE
NoSuchMethodError currentBinaryVersion For ScalaJs 1.0.0

### ISSUE THREAD

**Issue by FabioPinheiro** [ScalablyTyped/Converter#113]
The Converter SBT plugin does work for scala version 1.0.0

https://github.com/ScalablyTyped/Converter/blob/master/sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala#L100

is using a method that what removed on commit:

https://github.com/scala-js/scala-js/commit/61e7bfa25eb4296d5ac3ec1e5bd1889479be1e63

This is causing https://github.com/ScalablyTyped/Demos/issues/21

**Comment by FabioPinheiro** [comment]
The folder name `sbt-converter06` raise me some red flag maybe I'm doing something wrong

**Comment by oyvindberg** [comment]
`sbt-converter06` is by the way not really a red flag. The exact same source code it used for both versions of the plugin, and it's rather accidental that it ended up in the folder for 0.6. Once we have some source incompatibility between them I'll setup a shared folder instead
