### ISSUE TITLE
Broken doc links

### ISSUE THREAD

**Issue by benhutchison** [ScalablyTyped/Converter#126]
https://scalablytyped.org/ is [suggested as the place to go for docs](https://github.com/ScalablyTyped/SlinkyDemos/blob/master/build.sbt#L17) but it gives a 404

<img width="1250" alt="Screen Shot 2020-03-12 at 10 41 53 pm" src="https://user-images.githubusercontent.com/95460/76518224-d775cf80-64b2-11ea-9855-bbea953444cf.png">

**Comment by oyvindberg** [comment]
Thanks for the report. I'm aware, but found it practical to keep a somewhat low profile until the beta releases stabilize. Will keep the issue as a reminder :)

**Comment by benhutchison** [comment]
Be warned, it'll take more than vroekn doc links to stop me investigating the awesome potential of Scalably Typed

**Comment by oyvindberg** [comment]
Thank you @benhutchison :)

**Comment by oyvindberg** [comment]
fixed
