### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#129]
As reported over at gitter:
> Anthony Cerruti @srnb_gitlab Mar 10 01:46
> [error] PhaseRes.scala:84 Caught exception: Cannot run program "rm" (in directory "C:\Users\aprim"): CreateProcess error=2, The system cannot find the file specified [thread => 158, project => facaframe, ms => 39564, phase => build, id => std]java.io.IOException: Cannot run program "rm" (in directory "C:\Users\aprim"): CreateProcess error=2, The system cannot find the file specified

There will probably be a few more issues like this. I won't have the chance to work on this myself, but I'd be happy to provide guidance

**Comment by rossoha** [comment]
@oyvindberg  Please take a look if this is a suitable solution: https://github.com/ScalablyTyped/Converter/pull/132

**Comment by oyvindberg** [comment]
fixed in beta8
