### ISSUE TITLE
interpolated string in ts file seems to get translated into a complex typing that is not as string

### ISSUE THREAD

**Issue by aappddeevv** [ScalablyTyped/Converter#147]
I'm not sure the details, but I have an interpolated string that is fully resolved inside of typescript in the sense that 

```typescript
import {oh_no} from "./my_config_vars"

export const foo = `this is a really long string ${oh_no}`
```

In generated code I'm getting a `Toplevel` construct that appears to breakdown the string into actual classes including newlines, etc. Can't quite tell but since the string is fully resolved I'm guessing it should just export it normally as a string reference. I noticed that another string I export using backtick but does not have any interpolation and is exported as `Toplevel[String]` as expected.

Is this an issue or is this just a generation artifact? I actually need it as a string.

I resolved this by specifically indicating the type is a string and it output the expected result, i.e., 

```typescript
export conts foo: sting = `...`
```
But not everyone can probably go back and change sources.

**Comment by oyvindberg** [comment]
Interesting! Can you dig out what ends up in the d.ts file?

**Comment by aappddeevv** [comment]
I tracked it down. 

The issue is that if the declaration does *not* have interpolation (I was wrong in my original statement) and you are exporting the backticked string, you get the error and its partly due to typescript.

The declaration

```typescript
export const foo = `
some string with no sliced in values
`
```
is output as `.d.ts`

```typescript
export const foo = "\nsome string with no slide values\s"
```
which is then generated as scala
```scala
val foo: `Linefeed...`
```
in one place. Then in the "strings" object:
```scala
sealed trait `Linefeed...`
```
which is a symbol in place where a type should be. 

So I think it then becomes a literal type.

**Comment by oyvindberg** [comment]
Aha. That's true - I should have thought of that. 

As you figured out, `const someString = "someValue"` receives a literal type type now and get that treatment you saw. 

I'm not sure if that's good. It would be easy to change it to `String` with a comment saying what the content is. 
Or widen to `String` if the string value is "ugly" for some definition of ugly
and/or perhaps give it type `String with libStrings.someValue`.

**Comment by aappddeevv** [comment]
I think that if it is a literal, then the type should derived from that literal. We should probably sit on this a bit more though since there may be some typescript reason for it. I'll open a typescript ticket.

**Comment by aappddeevv** [comment]
The ts people said this was expected behavior but I'm not sure what means for the converter.

**Comment by oyvindberg** [comment]
Wait a bit until you escalate things to them please. The decision to widen the type to string or not is fully on our side :)

**Comment by aappddeevv** [comment]
They did respond, they said it was expected behavior.

**Comment by oyvindberg** [comment]
I changed the encoding to this:
`const URI = "Either"` => `val URI: /* "Either" */ String = js.native`
