### ISSUE TITLE
Link this Bintray plugin to the sbt organization

### ISSUE THREAD

**Issue by vmunier** [ScalablyTyped/Converter#150]
Hi @oyvindberg,

Thank you for this great plugin!

Would it be possible to link this Bintray Converter plugin to the sbt organization? https://www.scala-sbt.org/1.x/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization

Once linked, any releases of your plugin will automatically appear in the community sbt repository. The resolver `Resolver.bintrayRepo("oyvindberg", "converter")` would no longer be required.

Thanks!

**Comment by oyvindberg** [comment]
Hey there @vmunier 

Cool, I had no idea that could be done :)

I'll either do that or actually push to maven central directly before 1.0 :)

**Comment by tOverney** [comment]
That sounds great, I would profit from this too! Do you have a timeline on this?

**Comment by oyvindberg** [comment]
I consider it a pretty cosmetic change with a non-zero amount of effort to make it happen, so eventually I guess

**Comment by vmunier** [comment]
Hi,

Here's another reason of why it'd be useful to have this plugin in the sbt organization, which I should have mentioned before.

Some companies use private proxy repositories, which give them some degree of control of what libraries can be used.

These repositories are configured with a small set of verified resolvers, like the official SBT plugin resolver at https://dl.bintray.com/sbt/sbt-plugin-releases/, but do not include this plugin's resolver.

Linking this Converter Bintray plugin to the sbt organization means that any releases in https://dl.bintray.com/oyvindberg/converter/ will automatically appear in the community sbt repository https://dl.bintray.com/sbt/sbt-plugin-releases/ without any interventions from your side.

As a result, the `Resolver.bintrayRepo("oyvindberg", "converter")` resolver is not longer required, since the plugin can now be downloaded from the default `https://dl.bintray.com/sbt/sbt-plugin-releases`.

**Comment by oyvindberg** [comment]
So sorry, I forgot to get back to this. I had a look @vmunier and it looked like I had to link on a package by package basis? I distribute ~10 packages, so that felt like the wrong solution

**Comment by vmunier** [comment]
No worries @oyvindberg! 

I think the SBT plugin (sbt-converter) could be linked to the sbt organization, while the other packages/libraries (importer, phases, logging, etc.) could be published to Maven Central.

Alternatively, as you mentioned in an earlier comment, you could also publish everything to Maven Central if that's more convenient.

**Comment by oyvindberg** [comment]
Well now it's going on maven central, so this can be closed :)
