### ISSUE TITLE
cli beta12 links to strange lib versions

### ISSUE THREAD

**Issue by aappddeevv** [ScalablyTyped/Converter#152]
After running `sbt publishLocal` the beta12 seems to want a strange lib:
```sh
 not found: https://repo1.maven.org/maven2/io/circe013/circe-jackson29_2.12/0.13.0/circe-jackson29_2.12-0.13.0.pom
```
Where the circe013 is the strange part.

**Comment by oyvindberg** [comment]
So I manually shaded circe and published it to bintray after repeated problems with people using the sbt plugin along with other sbt plugins using either older or newer versions of it.

I just checked out the converter in a fresh user directory and successfully managed to `publishLocal` from `master`. Can you please pull newest, clean and try again? And if it keeps not working, what does `show resolvers` say in sbt?

**Comment by aappddeevv** [comment]
Did fresh. This is the CLI, not sbt. Same error.

Looks like I need to publish the shaded libs as well. Not sure how to do that.

**Comment by oyvindberg** [comment]
What command exactly are you running where it fails?

I `publishLocal`ed the CLI on that machine and ran it with coursier `cs launch -r ivy2local stc:1.0.0-beta12+3-c367cba6` and it just worked. 

If it helps this is how you tell sbt to look where I published them
```
resolvers += Resolver.bintrayRepo("oyvindberg", "converter"),
```

**Comment by aappddeevv** [comment]
Ah, I just added to the coursier command line `-r bintray:oyvinberg/converter` which worked.
