### ISSUE TITLE
How can I change style using material-iu?

### ISSUE THREAD

**Issue by mvillafuertem** [ScalablyTyped/Converter#153]
I have this example but I would like to use the material-ui style. For example: `color=primary`. 

```
@react class SlinkyButton extends Component {

  case class Props(name: String)

  case class State(n: Int)

  override def initialState = State(n = 1)

  def acc(): Unit = setState(state => state.copy(state.n + 1))

  override def render(): ReactElement =
    div(
      Mui.TextField.StandardTextFieldProps(value = state.n.toString, disabled = true),
      Mui.Button(
        style := js.Dynamic.literal(
          fontSize = "20px",
          backgroundColor = "#234563",
          color = "#FFF"
        ),
        onClick := acc _
      )(s"Increment it, ${props.name}")
    )

}

```

**Comment by oyvindberg** [comment]
I'm interested in having a look at this, but it'll have to be a bit later. I'm currently spending my time improving the slinky flavour itself, and then updating demos and docs :)

**Comment by oyvindberg** [comment]
Here you go: https://github.com/ScalablyTyped/SlinkyDemos/commit/58c76658ce751f688509d1338dbbab1acabb63a8

Note that the code requires beta13 which I'll release soon

**Comment by mvillafuertem** [comment]
awesome work! thanks

**Comment by mvillafuertem** [comment]
> Here you go: [ScalablyTyped/SlinkyDemos@58c7665](https://github.com/ScalablyTyped/SlinkyDemos/commit/58c76658ce751f688509d1338dbbab1acabb63a8)
> 
> Note that the code requires beta13 which I'll release soon

awesome work! thanks
