### ISSUE TITLE
compability with com.github.japgolly.scalajs-react:1.7.0 ?

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#154]
I'm on beta12 and trying to upgrade to `com.github.japgolly.scalajs-react:1.7.0` (I want to update to antd:4.x which needs react 16.12+) but run into heaps of qualifier issues with antd, e.g.:

`[warn] TsTreeScope.scala:83 Cannot resolve TsQIdent(IArray(TsIdentSimple(React), TsIdentSimple(ReactNode))) [thread => 2934, project => service1UiClient, ms => 48362, phase => typescript, scope => TreeScope(TsParsedFile() / TsDeclModule(antd/lib/upload/interface) / TsExport() / TsExporteeTree() / TsDeclInterface(UploadProps) / TsMemberFunction(iconRender) / TsFunSig() / TsTypeRef()), id => antd]`

This leads to components not being generated.

This is with sjs0.6, using sjs1 I'm getting resolution errors:
`PhaseRunner.scala:90 Failure, [std => sbt.librarymanagement.ResolveException: Error downloading com.github.japgolly.scalajs-react:core_sjs1_2.13:1.5.0`.

To me it seems the converter is still depending on scalajs-react:1.5.0 as in https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/Versions.scala#L10 ?

Using scalajs-react:1.6.0 with antd:3.x works fine on sjs0.6

Let me know if you need a minimal reproduction.

**Comment by oyvindberg** [comment]
They might have changed something in the newest version of the react typings which causes those cannot resolve errors. I'll check it out

Otherwise I have a local branch with new scalajs-react and scala.js 1, will release within a few days

**Comment by oyvindberg** [comment]
Released now as 1.0.0-beta13, let me know if there are further issues :)
