### ISSUE TITLE
Incorrect Scaladoc generated in a few cases

### ISSUE THREAD

**Issue by rpiaggio** [ScalablyTyped/Converter#181]
Hi! I'm happily using `ScalablyTypedConverterGenSourcePlugin` from `1.0.0-beta18`.

Apart from one case in the specific lib I'm using, `std/{FunctionConstructor.scala, GeneratorFunction.scala, GeneratorFunctionConstructor.scala, PromiseConstructor.scala}` get generated with incorrect ScalaDoc.

Example from `FunctionConstructor`:
``` scala
@js.native
trait FunctionConstructor
  extends /**
  * Creates a new function.
  * @param args A list of arguments the function accepts.
  */
Instantiable1[/* args (repeated) */ java.lang.String, js.Function] {
  def apply(args: java.lang.String*): js.Function = js.native
}
```

This causes a `discarding unmoored doc comment` error when running `sbt doc` (which is run when publishing).

This is not urgent since I can disable doc generation when publishing.

Thank you for this awesome tool once again!

**Comment by oyvindberg** [comment]
You live you learn. This is not the first time I come across scala having strong opinions about what goes into a comment! You can not have a bunch of utf-8 encoded characters, you can not have nested `/* */` comments, and apparently now `/**` comments cannot legally be in any location.

The curious thing is that the placement is "correct", it's attached to the constructor, which since we're in a trait is rewritten to be another trait with an implicit conversion attached to it. I'm hesitant to move or remove it, but I think we can easily rewrite `/**` to `/*` in the "wrong" places. 

Could you please double check that changing your example into this:
```scala
@js.native
trait FunctionConstructor
  extends /*
  * Creates a new function.
  * @param args A list of arguments the function accepts.
  */
Instantiable1[/* args (repeated) */ java.lang.String, js.Function] {
  def apply(args: java.lang.String*): js.Function = js.native
}
```

will help? Thanks :)

**Comment by rpiaggio** [comment]
Hi @oyvindberg! I can confirm that changing `/**` to `/*` did help, it prevents the error from happening in the reported files.

However, ScalaDoc now moved on and reported other errors:

* In `gpp/std/VBArray.scala:26:3: Could not find any member to link for "1,2,3],[4,5,6".`:
``` scala
  /**
    * Returns a Javascript array with all the elements in the VBArray. If there are multiple dimensions,
    * each successive dimension is appended to the end of the array.
    * Example: [[1,2,3],[4,5,6]] becomes [1,2,3,4,5,6]
    */
  def toArray(): js.Array[T] = js.native
```

* In a bunch of places in `std/{Promise.scala, PromiseLike.scala, PromiseConstructor.scala}`: `Tag '@returns' is not recognised`. (I think that needs to be `@return`).

* In `std/Date.scala:20:3: Could not find any member to link for "{TypeError}"`:
``` scala
  /**
    * Converts a Date object to a string or number.
    *
    * @param hint The strings "number", "string", or "default" to specify what primitive to return.
    *
    * @throws {TypeError} If 'hint' was given something other than "number", "string", or "default".
    * @returns A number if 'hint' was "number", a string if 'hint' was "string" or "default".
    */
```

* In several places specific to the library I'm generating for (highcharts): `Tag '@fires' is not recognised`. Example:
``` scala
  /**
    * Export-data module required. View the data in a table below the
    * chart.
    *
    * @fires Highcharts.Chart#afterViewData
    */
  def viewData(): Unit = js.native
```

**Comment by oyvindberg** [comment]
Ok, I had a look and I see these as warnings, do you have fatal warnings on? 
Does `Compile / doc / scalacOptions -= "-Xfatal-warnings"` help?

If that is enough I'll leave it at that. scaladoc is really the wrong tool for this, but it's of course nice to not break peoples builds.

**Comment by rpiaggio** [comment]
Yes, I have fatal warnings on. I can disable them for scaladoc.

Thank you very much!
