### ISSUE TITLE
Incomplete generation of antd TabsProps

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#185]
The behaviour can be observed in https://github.com/ScalablyTyped/ScalaJsReactDemos .

It seems the TabProps from https://github.com/ant-design/ant-design/blob/master/components/tabs/index.tsx is not correctly converted and misses the inherited fields from https://github.com/react-component/tabs/blob/master/src/Tabs.tsx (which is aliased to RcTabsProps, maybe here lies the issue?)

Looking at `.ivy2/local/org.scalablytyped/antd_sjs1_2.13/4.3.1-c05847/srcs/antd_sjs1_2.13-sources.jar!/typings/antd/tabsMod/TabsProps.scala`, there's an error comment at the top:

```scala
/* import warning: RemoveDifficultInheritance.summarizeChanges 
- Dropped {[ P in std.Exclude<keyof / * import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify RcTabsProps * / any, 'editable'> ]: / * import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify RcTabsProps * / any[P]} */
```

Futhermore the TabPane component is missing in the antd components. Is that intended as it's just a type alias to the rc-tabs/TabPane? So I should use the rc-tabs/TabPane directly?

**Comment by oyvindberg** [comment]
Thanks for the report.

It's not so easy to understand through the debug logging, but the main clue is this:
> transforms.QualifyReferences#resolveTypeRef many Couldn't qualify RcTabsProps 

which means that the implementation of the module system failed to resolve `RcTabsProps`, and the props end up as `js.Any`. I'll see if that can be fixed

**Comment by oyvindberg** [comment]
I had a look now and found it, it seems all/most of the `rc-*` libraries define `main` and `module` in their `package.json` and not `types`/`typings` as I expected. Will add support for that and release shortly :)
