### ISSUE TITLE
error with BigInt

### ISSUE THREAD

**Issue by mvillafuertem** [ScalablyTyped/Converter#200]
Hi @oyvindberg, when I try use the converter with `@types/node-sass` and `@types/node` I get this error. Thanks in advice.

```
[error] ZincCompiler.scala:199 [Error] /scalajs-react-world/modules/journal/target/streams/_global/stImport/_global/streams/sources/n/node/src/main/scala/typings/node/fsMod/BigIntStats.scala:4: object BigInt is not a member of package typings.std [project => journal, ms => 32682]
[error] ZincCompiler.scala:199 [Error] /scalajs-react-world/modules/journal/target/streams/_global/stImport/_global/streams/sources/n/node/src/main/scala/typings/node/processMod/global/NodeJS/HRTime.scala:3: object BigInt is not a member of package typings.std [project => journal, ms => 35646]
[error] ZincCompiler.scala:199 three errors found [project => journal, ms => 36776]

```

**Comment by oyvindberg** [comment]
Can you try to add an entry to `stStdLib` which contains BigInt? It's fairly new I think. Also if it's added to scalajs-dom by now that should probably be used instead

**Comment by exoego** [comment]
FYI js.BigInt is now a part of Scala-js library https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/js/BigInt.scala

**Comment by oyvindberg** [comment]
Aha thanks @exoego :) so we use should that directly then

**Comment by oyvindberg** [comment]
I updated the demos to use newest node with `stStdLib := List("esnext")` here https://github.com/ScalablyTyped/Demos/commit/0dd24ff4a197a9d29d3b61fe3b80d61c811a5e6b
