### ISSUE TITLE
Problem converting tui-chart

### ISSUE THREAD

**Issue by gmixa** [ScalablyTyped/Converter#249]
Hi I Try to use tui -chart wit scalable typed
My Setup is:

lazy val example5 = project.enablePlugins(ScalaJSPlugin,ScalaJSBundlerPlugin,ScalablyTypedConverterPlugin)
  .configure(browserProject)
  .settings(
    Compile / npmDependencies ++= Seq(
      "@toast-ui/chart" -> "4.0.4"
    )

I use the following plugins:

addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.4.0")

addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")

resolvers += Resolver.bintrayRepo("oyvindberg", "converter")

addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta29.2")

during the set code creation process i see no error messages
and finally this gets created in default.scala:

package typings.toastUiChart.mod

import typings.toastUiChart.mod.toastui.Chart
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@toast-ui/chart", JSImport.Default)
@js.native
class default () extends Chart
/* static members */
@JSImport("@toast-ui/chart", JSImport.Default)
@js.native
object default extends js.Object {
  
  def areaChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify AreaChartProps */ js.Any
  ): AreaChart = js.native
  
  def barChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify BarChartProps */ js.Any
  ): BarChart = js.native
  
  def boxPlotChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify BoxPlotChartProps */ js.Any
  ): BoxPlotChart = js.native
  
  def bubbleChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify BubbleChartProps */ js.Any
  ): BubbleChart = js.native
  
  def bulletChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify BulletChartProps */ js.Any
  ): BulletChart = js.native
  
  def columnChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify ColumnChartProps */ js.Any
  ): ColumnChart = js.native
  
  def columnLineChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify ColumnLineChartProps */ js.Any
  ): ColumnLineChart = js.native
  
  def heatmapChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify HeatmapChartProps */ js.Any
  ): HeatmapChart = js.native
  
  def lineAreaChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify LineAreaChartProps */ js.Any
  ): LineAreaChart = js.native
  
  def lineChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify LineChartProps */ js.Any
  ): LineChart = js.native
  
  def lineScatterChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify LineScatterChartProps */ js.Any
  ): LineScatterChart = js.native
  
  def nestedPieChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify NestedPieChartProps */ js.Any
  ): NestedPieChart = js.native
  
  def pieChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify PieChartProps */ js.Any
  ): PieChart = js.native
  
  def radarChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify RadarChartProps */ js.Any
  ): RadarChart = js.native
  
  def scatterChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify ScatterChartProps */ js.Any
  ): ScatterChart = js.native
  
  def treemapChart(
    props: /* import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify TreemapChartProps */ js.Any
  ): TreemapChart = js.native
}

That way i cannot set up the library to be used.
To me it seems as this problem is somehow similar to a previously reported issue.
I think its somehow related to Issue #185

**Comment by oyvindberg** [comment]
Hi there, thanks for the report.

Those type definitions are broken. They use some local [templating](https://github.com/nhn/tui.chart/blob/main/apps/chart/tsconfig.json#L14) of module names. 

```typescript
import { LineScatterChartProps } from '@src/charts/lineScatterChart';
```

That's a very.... javascript thing to do in itself, and it's not (currently) supported by the ST converter. Even worse, these module rewrites or whatever they are called are not (afaict) propagated into the npm module, so tooling like intellij and I guess even typescript itself breaks.

I'd raise an issue in their repo

**Comment by gmixa** [comment]
Ok, thanks for the quick respond. I am no TypeScript Expert so after i found a bug that looked similar in this project, and as i am actually using it, I thought it might be an issue with the converter!
