### ISSUE TITLE
Migration from bintray

### ISSUE THREAD

**Issue by narma** [ScalablyTyped/Converter#262]
Bintray will be disabled soon: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by oyvindberg** [comment]
Thank you, an issue was necessary to track this.

List of things which need to be done:
- Publish the converter to maven central. This is easy (the runtime artifact is already there), except that there currently is a manually shaded fork of circe 0.13 on bintray, which I don't want to publish to maven central in it's current form. This was/is absolutely necessary to coexist with other sbt plugins, unfortunately. Research is needed how other sbt plugins shade dependencies.
- The CLI tool supports publishing jars directly to users bintray. All the publication code needs to be scrapped and rewritten for that functionality to keep working. Note that this is most probably relatively easy to do, we just need to integrate with other libraries. I'm not using this functionality myself, so this is a great area for those who use it to contribute. The file in question is [here](https://github.com/ScalablyTyped/Converter/blob/master/importer/src/main/scala/org/scalablytyped/converter/internal/importer/build/BinTrayPublisher.scala). Ideally we pick something which can publish to all kinds of repos

**Comment by oyvindberg** [comment]
snapshots are now available at sonatype s01
```
resolvers += MavenRepository("sonatype-s01-snapshots", "https://s01.oss.sonatype.org/content/repositories/snapshots")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta30+29-bd7edd1b-SNAPSHOT")
```

release to maven central should follow soonish

**Comment by oyvindberg** [comment]
now coursier can hopefully upgrade as well https://github.com/coursier/apps/pull/89

**Comment by oyvindberg** [comment]
Fully fixed in beta32
