### ISSUE TITLE
Weird types in constructors generated for react-virtualized

### ISSUE THREAD

**Issue by AlexITC** [ScalablyTyped/Converter#281]
Importing [react-virtualized](https://github.com/bvaughn/react-virtualized/) leads to weird types in constructors, for example, this is the `Table` constructor:

```scala
  def apply(
    headerHeight: Double,
    height: Double with js.UndefOr[Double],
    onScroll: (js.UndefOr[js.Function1[/* params */ ScrollParams, _]]) with (js.UndefOr[js.Function1[/* info */ ScrollEventData, Unit]]),
    rowCount: Double,
    rowHeight: Double | (js.Function1[/* params */ Index, Double]),
    scrollToAlignment: js.UndefOr[Alignment] with js.UndefOr[String],
    width: Double with js.UndefOr[Double]
  ): Builder
```

In this case, `Double with js.UndefOr[Double]` can't be constructed, instead `js.UndefOr[Double]` should be enough.

This can be reproduced by including the following npm dependencies:

```
Compile / npmDependencies ++= Seq(
   "react-virtualized" -> "9.22.3",
   "@types/react-virtualized" -> "9.21.11")
```

**Comment by oyvindberg** [comment]
I found a good enough fix for this now, so it looks like this
```scala
  @scala.inline
  def apply(
    headerHeight: Double,
    rowCount: Double,
    rowHeight: Double | (js.Function1[/* params */ Index, Double])
  ): Builder = {
    val __props = js.Dynamic.literal(headerHeight = headerHeight.asInstanceOf[js.Any], rowCount = rowCount.asInstanceOf[js.Any], rowHeight = rowHeight.asInstanceOf[js.Any])
    new Builder(js.Array(this.component, __props.asInstanceOf[TableProps]))
  }
```

In the general case it's difficult to solve perfectly, since in a case like this with two conflicting definitions of `height`, `onScroll` and so on we should pick the most narrow type I suppose, though I'd need to experiment how TS actually does this.

**Comment by AlexITC** [comment]
what about the `height: Double with js.UndefOr[Double]` argument? I guess `js.UndefOr[Double]` should be enough.

Thanks!

**Comment by oyvindberg** [comment]
By the new interpretation `height` is now an optional member, and optional members are set afterwards
```scala
`Table(headerHeight = 1, rowCount = 1, rowHeight = 1).height(1)
```

Like i hinted at in the last comment I'm not really sure if it's entirely correct. I'm probably going forward with this regardless, as it's better than before in any case.
