### ISSUE TITLE
Support Scala 3

### ISSUE THREAD

**Issue by arashi01** [ScalablyTyped/Converter#314]
Now that Scala 3 is GA, attempted to upgrade an existing project to Scala 3 and received the following error on all projects with ScalablyTyped enabled:

`[error] (PROJECTNAME / stInternalZincCompiler) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-compiler:3.0.0
`

**Comment by oyvindberg** [comment]
Thanks. As you might imagine, it's a bigger undertaking. the work is tracked in #202 .

For now I've had reports that it's possible to generate jars for 2.12 with the CLI tool and add them to your build with dotty compat. ETA on the scala 3 support is still a few weeks off, seems it'll have to wait for 3.0.1 now.

**Comment by arashi01** [comment]
@oyvindberg Sorry, for some reason my search didn't bring up that issue. Will close this one.

**Comment by adamsar** [comment]
Actually this issue is fine I think, the work tracked to fix this issue is in PR 202
