### ISSUE TITLE
ZincCompiler does not resolve the correct artifacts for Scala 3

### ISSUE THREAD

**Issue by vincenzobaz** [ScalablyTyped/Converter#323]
When using the plugin with a Scala 3 project, the following error is raised:
```
[error] (example / stInternalZincCompiler) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-compiler:3.0.0
[error]   Not found
[error]   not found: /home/vinz/.ivy2/local/org.scala-lang/scala-compiler/3.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/3.0.0/scala-compiler-3.0.0.pom
[error] Total time: 1 s, completed Jun 21, 2021, 10:05:44 AM
```
In Scala 3, the name of the artifact should be `scala3-compiler`

**Comment by oyvindberg** [comment]
Thanks @vincenzobaz . I'm working towards scala 3 support in #202 . Expecting release within a few weeks

**Comment by vincenzobaz** [comment]
Great news, I am looking forward to that!
Fixing this issue would allow to reuse Scala 2.13 typings with Scala 3, but generating the typings taking full advantage of all the new language features sounds awesome.

**Comment by sbrunk** [comment]
@vincenzobaz as a workaround you should be able to generate the 2.13 typings with the [cli](https://scalablytyped.org/docs/cli) and then add the generated deps. The CLI even outputs a `libraryDependencies` snippet for sbt when you run it, you just need to add `.cross(CrossVersion.for3Use2_13)` and it should work just fine.

**Comment by oyvindberg** [comment]
Released in beta34
