### ISSUE TITLE
Enable generated sources to be `private[pkg]`

### ISSUE THREAD

**Issue by armanbilge** [ScalablyTyped/Converter#329]
As discussed in https://github.com/typelevel/fs2/pull/2453#discussion_r667388562.

I'd be happy to make a PR, but could use a pointer where this would go 😅  obviously this will need an SBT setting, and where does the actual source-generation happen?

**Comment by oyvindberg** [comment]
Hey, just some feedback here. I implemented this, but didn't have the time to finish the PR. Will try to land it soon

**Comment by armanbilge** [comment]
Wow! thanks for the update and for your efforts on this 😁
