### ISSUE TITLE
withRef and Any

### ISSUE THREAD

**Issue by dispalt** [ScalablyTyped/Converter#401]
So this just tripped me up with the change to `Any`, specifically this.  https://github.com/ScalablyTyped/Converter/blob/f18e6850672bda4460b5460ced6ce8cac69f328e/tests/react-transition-group/check-slinky-3/r/react/src/main/scala/typingsSlinky/StBuildingComponent.scala#L48

That function should probably require a conversion at least, right?

**Comment by oyvindberg** [comment]
Absolutely!

I figured there would be some kind of fallout from that change, and here it is. the fix should be easy enough at least. 

you can call `.set("ref", ...)` with a `js.Function1` as a workaround
