### ISSUE TITLE
Improve `import-problems` documentation

### ISSUE THREAD

**Issue by fdietze** [ScalablyTyped/Converter#409]
Ideas to improve the documentation (https://scalablytyped.org/docs/import-problems):
- mention `stdlib.d.ts`
- `testOnly org.scalablytyped.converter.internal.importer.ImporterTest` did not work for me (NixOS, JDK 17). I was able to run the tests after switching to ubuntu, java 1.8 and running `testOnly org.scalablytyped.converter.internal.importer.ImporterTest213`. I don't know exactly what was the issue, though...

**Comment by oyvindberg** [comment]
Just in case anyone else stumbles over this issue, I'm copying in the answer from another issue.

>    root> testOnly org.scalablytyped.converter.internal.importer.ImporterTest
>
> This was written before scala 3 support was added. now that test is a trait with two concrete implementations, ImporterTest213 and ImporterTest3. These tests are snapshot tests, that is they generate a lot of code, compile it, and all that code is checked in. CI then checks that the generated checked in code matches what is generated when running the test. As such this covers a whole lot of ground, testing wise. I think snapshot tests are incredibly powerful, and allows me to test so much with so little effort.
ImporterTest213 is kept around to ensure that code still compiles for Scala 2.13, but the results are not checked in.

**Comment by oyvindberg** [comment]
Leaving this open until docs are improved
