### ISSUE TITLE
Error importing antd 4.19.2

### ISSUE THREAD

**Issue by nafg** [ScalablyTyped/Converter#428]
`[error] ImportTree.scala:394 message Unsupported index type TypeRef(QualifiedName(IArray(Name(<string_literal>))),IArray(TypeRef(QualifiedName(IArray(Name(data-${string}))),IArray(),NoComments)),NoComments) [threa
d => 782, project => js, ms => 154846, phase => scala.js, scope => TreeScope(TsParsedFile() / TsDeclModule(antd/lib/input/Input) / TsDeclInterface(InputProps) / TsMemberIndex()), id => antd]com.olvind.logging.Logg
er$LoggedException: Unsupported index type TypeRef(QualifiedName(IArray(Name(<string_literal>))),IArray(TypeRef(QualifiedName(IArray(Name(data-${string}))),IArray(),NoComments)),NoComments)`

**Comment by oyvindberg** [comment]
Thanks for the report. 

This is an easy thing to fix, we can just change the fallback case to `String` instead of erroring out for now. real support for template literal strings is for another day

**Comment by oyvindberg** [comment]
This was fixed in f6a7e281
