### ISSUE TITLE
Instantiable23 type not found

### ISSUE THREAD

**Issue by FabioPinheiro** [ScalablyTyped/Converter#438]
I got a error  type `Instantiable23` not found. From the generated code of a underlying typescript dependency of the dependency that I want to use.
```sbt
[error] 284 |  var FileOptions: (Instantiable23[
[error]     |                    ^^^^^^^^^^^^^^
[error]     |                    Not found: type Instantiable23]), Problem(/home/fabio/workspace/fmgp-ipfs/webapp/target/streams/_global/stImport/_global/streams/sources/i/input-output-hk__atala-prism-sdk/src/main/scala/typings/inputOutputHkAtalaPrismSdk/anon/Typeofwkt.scala:[52098..52112], Not found: type Instantiable23, Error, Optional[-- [E006] Not Found Error: /home/fabio/workspace/fmgp-ipfs/webapp/target/streams/_global/stImport/_global/streams/sources/i/input-output-hk__atala-prism-sdk/src/main/scala/typings/inputOutputHkAtalaPrismSdk/anon/Typeofwkt.scala:795:18 
```

I see the Instantiable classes until number 22 on https://github.com/ScalablyTyped/Converter/blob/master/import-scalajs-definitions/src/test/resources/imported/org.scala

I'm assuming this is a limitation not a bug.
Is there way to remove this limitation or does it require to much work and playing around with scala2 macros?

In term of workarounds what can I do?
- add Instantiable23 class to the plugin and use a self build version of the plugin.
- use `stIgnore` to ignore the full underlying typescript dependency. (but I wanted some other types from that dependency).
- modified the underlying typescript dependency so that type that generantes code with `Instantiable23` to type `any`

**Comment by oyvindberg** [comment]
haha, 23 constructor parameters! I guess nothing should surprise me anymore.

`InstantiableN` is defined [here, with sbt-boilerplate](https://github.com/ScalablyTyped/Runtime/blob/master/src/main/boilerplate/ScalablyTyped/runtime/instantiables.template). 22 is at least the default value for sbt-boilerplate, I suppose it can be increased. 

That said, this is an edge case, and I'd be happy with setting this to `any`. That can be done [here](https://github.com/ScalablyTyped/Converter/blob/master/importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ImportType.scala#L304-L334). 

We can do something like this:
```scala
    if (sig.params.length > 22)
      TypeRef.Any.withComments(
        Comments(s"/* untranslatable newable function with more than 22 parameters: ${TsTypeFormatter.sig(_sig)} */"),
      )
    else
      TypeRef(
        QualifiedName.Instantiable(sig.params.length),
        params :+ ret,
        comments,
      )
```

**Comment by FabioPinheiro** [comment]
That seems a good solution to me.
It does not fix it but also does not stop de compilation.
