### ISSUE TITLE
Feature request: allow customization of node_modules location

### ISSUE THREAD

**Issue by Lasering** [ScalablyTyped/Converter#447]
When using ScalablyTypedConverterExternalNpmPlugin the `externalNpm` "Runs npm and returns the folder with package.json and node_modules". However the folder with package.json might be different from the folder containing node_modules (for example in yarn you can set the node_modules location with the `--modules-folder`).

The plugin could have a settingKey allowing customization of the node_modules location. I can make a PR if it helps.

**Comment by oyvindberg** [comment]
Why would you want to do that? :D

**Comment by Lasering** [comment]
My `externalNpm` is:
```
externalNpm := {
  Process(s"yarn --non-interactive --strict-semver --prefer-offline --modules-folder ${target.value}/node_modules", baseDirectory.value).!
  baseDirectory.value
},
```
This way when I do `clean` I also clean the node_modules so it is really a clean.

**Comment by oyvindberg** [comment]
I suggest your `externalNpm` copy your `package.json` into `target.value` and return that folder instead of `baseDirectory`.

**Comment by Lasering** [comment]
That solves it, but now the authoritative `package.json` is the one in `target.value` which may lead to synchronization problems (me editing the package.json outside and things not working because somehow the file is not being copied).

The default value for the new setting can still remain `InFolder(os.Path(externalNpm.value) / "node_modules")`, thus the usability of the plugin would remain the same with the improved configurability of the node modules location.

**Comment by oyvindberg** [comment]
you've got to give me some motivation for what you're trying to accomplish by doing this, because I don't see it

**Comment by Lasering** [comment]
If I implement this feature and do a PR would you consider merging it?

**Comment by Lasering** [comment]
I'm interested in having this feature to the point of be willing to implement it myself, however if that won't be something you are willing to merge I don't like to work just to warmup. I understand you might not want to gain the burden of maintaining this feature in the future, just be clear about it.

**Comment by oyvindberg** [comment]
that's my definition of "broken", when you and your colleagues all need to remember how to tell each tool about the convention-breaking change you've done.

I suppose that would work, but that's quite a handful to maintain. Anyways, I'll leave you to it :)
