### ISSUE TITLE
sbt 1.7 support

### ISSUE THREAD

**Issue by kubukoz** [ScalablyTyped/Converter#457]
Hi, sbt released a 1.7 version, but on the `1.0.0-beta38` release I'm getting this:

```
[error] This version of the ScalablyTyped plugin only supports sbt 1.5.x or 1.6.x. You're currently using 1.7.0
```

Can you release a 1.7-compatible version? Thanks :)

**Comment by oyvindberg** [comment]
Hey there!

Absolutely, I'll get it out soon. At least as long as they didn't break bincompat again :)

**Comment by kubukoz** [comment]
one would hope :D did they do it in a 1.x release? Or is there another reason why you're listing the supported versions explicitly?

**Comment by oyvindberg** [comment]
No such check was ever introduced without preceding breakage :D 

The change to virtual paths in 1.4 or 1.5, don't remember exactly, broke everything. And I got a lot of bug report s with ugly stack traces. That's why the check is there

**Comment by an-tex** [comment]
> ```
> java.lang.NoClassDefFoundError: okhttp3/Authenticator
> ```

yep they dropped the okhttp dependency in https://github.com/sbt/librarymanagement/pull/399 . guess would be ok to add it explicitly here?

**Comment by an-tex** [comment]
well they actually migrated to use gigahorse apachehttp instead due to https://github.com/sbt/sbt/issues/6912 . i wonder if that might be the better option here too? might be just a patter of package import changes

**Comment by an-tex** [comment]
another issue popped up 
```
java.lang.NoClassDefFoundError: sbt/internal/librarymanagement/JavaNetAuthenticator
	at org.scalablytyped.converter.internal.RunCache$mehttp$.http$lzycompute(RunCache.scala:268)
```
this file has been removed in the process of dropping the okhttp dependency. i'm playting around with the migration to apachehttp

**Comment by oyvindberg** [comment]
I'm bumping everything to sbt 1.7.1 and gigahorse with apache http @an-tex , expect a PR soon. thanks for having a look :)

**Comment by oyvindberg** [comment]
nice, that's line by line what I ended up with :)

**Comment by an-tex** [comment]
haha apparently apachehttp is unlike rome. only one road... ;)

**Comment by oyvindberg** [comment]
published in https://github.com/ScalablyTyped/Converter/releases/tag/v1.0.0-beta39
