### ISSUE TITLE
Publish type declarations for Distribution in Sonatype

### ISSUE THREAD

**Issue by jvican** [ScalablyTyped/Converter#479]
Would it be possible to publish all type declarations in https://github.com/ScalablyTyped/Distribution to Sonatype? This would be a great improvement over the status quo where we need to run things locally and we can't easily push scripts or Scala.js code written to repositories and have them compile with GitHub actions. It also helps with reproducibility.

Ideally, ScalablyType would have its own organization and all of the jars would be published under that name. The job that does the publishing might take a long time... but given that it worked before for Bintray (from what I see in some tickets and docs), I think it's doable.

**Comment by oyvindberg** [comment]
No, I've decided not to do that.

- I don't think it's fair to Sonatype to deploy tens to hundreds of thousands of artifacts where most of them will be downloaded 0 times. For bintray there was a job to clean out old artifacts, but that's not possible with maven central.
- the scope is just too big. Let's say we take the current set of thousands of libraries (which can easily be extended a lot). Each of them will be re-published on new versions, *and* on changes to the output from newer versions of the ST converter. And then there are the [flavours](https://scalablytyped.org/docs/flavour), which can do arbitrary code rewrites, especially replacing external type references. those could be published. And then ideally we would publish cross releases between 2.13 and 3. It's quickly approaching infinity :)

The solution I have in mind is that people use ST to generate some baseline for a library, improve it as necessary, and then publish to maven central, see https://scalablytyped.org/docs/library-developer . That way we have some manual curation of what's available, more specific documentation can be written and so on.

**Comment by jvican** [comment]
> The solution I have in mind is that people use ST to generate some baseline for a library, improve it as necessary, and then publish to maven central, see [scalablytyped.org/docs/library-developer](https://scalablytyped.org/docs/library-developer) . That way we have some manual curation of what's available, more specific documentation can be written and so on.

Right, but manual curation requires human intervention and time, and there's a shortage of OSS maintainers in general. I find it difficult people would be willing to do this unless for the 5 or 10 most important Typescript bindings.

Have you considered, instead, to have some way to publish these to S3 or some kind of public storage? Not sure how we could make it so that coursier can resolve these jars without them being in Sonatype (not sure it's possible at all).

The current solution is OK, I'm using it but has the drawbacks mentioned before, and it'd be nice if there was a higher degree of automation or configuration of stc if we're to live with this approach for a long time. Ideally, stc would take care of caching jars that have already been built in some kind of remote storage layer (that can be owned by users or orgs).

**Comment by oyvindberg** [comment]
It has functionality for that! :) See https://scalablytyped.org/docs/remotecache

**Comment by oyvindberg** [comment]
You can test it out by cloning [Demos](https://github.com/ScalablyTyped/Demos) and starting sbt and then run `update` or whatever command really. You should see it downloads everything

**Comment by jvican** [comment]
Great! I had missed that. I don't have any storage layer at this moment I can use it with but it's nice that we support this in principle 😄
