### ISSUE TITLE
Support sbt 1.8.x

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#498]
There might be an issue with:

> Changes with compatibility implications
> Updates to Scala 2.12.17 + Scala compiler 2.12.17, which upgrades to scala-xml 2.x https://github.com/sbt/sbt/pull/7021

due to https://github.com/ScalablyTyped/Converter/issues/481

**Comment by oyvindberg** [comment]
Yeah, now let's get it done!

I guess this bumps the requirement for ST to sbt 1.8 just to avoid problems :)
