### ISSUE TITLE
Some classes are exported as traits

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#505]
from discord:

> TheElectronWill — Today at 1:32 PM
> Has the class encoding changed? I'm importing codemirror, and many TS classes are turned into traits by ST 1.0.0-beta40 🤔 
> For instance EditorView (https://github.com/codemirror/view/blob/aae5710d402702345e225fe70231ab505865142c/src/editorview.ts#L76), defined as export class EditorView { becomes
@js.native
trait EditorView extends StObject {
>
> without a companion object, thus I cannot use its constructor anymore :c

**Comment by oyvindberg** [comment]
Likely related 55b1a9df

**Comment by rochala** [comment]
Is there any chance for a fix for this issue in the near future? We're using ScalablyTyped in Scastie and this issue is a blocker for migrating into newer sbt version. Thanks.

**Comment by oyvindberg** [comment]
I reverted that commit in master since it broke more things, can you try newest master and see if it helps @rochala ?

Snapshot publishing looks broken after I migrated to github actions, so you'd have to `publishLocal` the converter yourself. 

If that works I can make a release straight away, otherwise it'll be a week or two

**Comment by rochala** [comment]
I tried it and everything is working as intended after revert.
Btw, thanks for working on ScalablyTyped. It turned out to be super useful for our needs!
