### ISSUE TITLE
Publish support for sbt 1.9.0, please?

### ISSUE THREAD

**Issue by SethTisue** [ScalablyTyped/Converter#541]
```
[scastie:error] java.lang.RuntimeException: This version of the ScalablyTyped plugin only supports 1.8.x. You're currently using 1.9.0
```

having this would be helpful to me over at https://github.com/scala/community-build/issues/1666

**Comment by oyvindberg** [comment]
Sure! I'll kick off a release tonight

**Comment by oyvindberg** [comment]
Ok, so the release pipeline apparently failed. Anyways I'm on it

**Comment by oyvindberg** [comment]
1.0.0-beta42 on the way to maven central now finally

**Comment by xerial** [comment]
@oyvindberg Thanks for releasing. The new version works with sbt 1.9.0 :)

**Comment by SethTisue** [comment]
scala/community-build@de99fa82ead98066b0fd25daa8c4bae8852b5fdb :+1:
