### ISSUE TITLE
Demos fail with: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by matthughes** [ScalablyTyped/Converter#546]
It seems all the ScalajsReact and Slinky demos fail with the following error.  This is using Node version v20.4.0.  Seems to a bug with older version of [Webpack](https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/).  Perhaps we should switch the projects off scalajs-bundler/webpack to using Vite as that seems more and more the direction the community is going?

```
[info] compiling 2 Scala sources to /Users/MHughe008/Opensource/scalablytyped/ScalaJsReactDemos/react-dnd/target/scala-3.2.2/classes ...
[info] Fast optimizing /Users/MHughe008/Opensource/scalablytyped/ScalaJsReactDemos/react-dnd/target/scala-3.2.2/react-dnd-fastopt
[info] Writing scalajs.webpack.config.js
[info] Bundling the application with its NPM dependencies
[error] node:internal/crypto/hash:69
[error]   this[kHandle] = new _Hash(algorithm, xofLen);
[error]                   ^
[error] Error: error:0308010C:digital envelope routines::unsupported
[error]     at new Hash (node:internal/crypto/hash:69:19)
[error]     at Object.createHash (node:crypto:138:10)
```

**Comment by matthughes** [comment]
FWIW, I tried using cli version 5.1.4 but seem to have the same error.

**Comment by oyvindberg** [comment]
Sorry, was inattentive here.

I came across this now as well on a new system. 
I applied this webpack version:
```
webpack / version := "5.88.2"
```
and a recent node, and at that point it did work.

porting all the demos to vite would be great, but I don't have the bandwidth myself
