### ISSUE TITLE
How can I utilize the ``Web3Provider.on`` function in ``Ethers.js``?

### ISSUE THREAD

**Issue by web3rakko** [ScalablyTyped/Converter#556]
I attempted to use the Web3Provider.on function in Ethers.js with the provided code snippet, but encountered a compilation error. Is there a solution available for this issue?
```scala
      Web3Provider.on(
        "network",
        (newNetwork: Any, oldNetwork: Any) => {
          dom.console.log("newNetwork:" + newNetwork)
          if (newNetwork.toString != chainId.toString) {
            openDialogBus.emit(true)
          }
        }
      )
```
Here is the error log:
```shell
[error] -- [E007] Type Mismatch Error: 
xxxxxxxxxxxxxxxx
[error] 39 |      meta.on("network", (newNetwork: Any, oldNetwork: Any)
[error]    |                         ^
[error]    |            Found:    (Any, Any) => Unit
[error]    |            Required: typings.ethersprojectAbstractProvider.mod.Listener
[error] 40 |      =>
[error] 41 |      {
[error] 42 |        dom.console.log("newNetwork:" + newNetwork)
[error] 43 |        if (newNetwork.toString != chainId.toString) {
[error] 44 |          openDialogBus.emit(true)
[error] 45 |        }
[error] 46 |      })
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 2023/08/20 17:37:05
```
Even after confirming the definition, I am unsure how to pass a second parameter of type ``typings.ethersprojectAbstractProvider.mod.Listener`` to the function. Could you please provide guidance on how to achieve this?

Here's the link to the definition for reference: [ethersprojectAbstractProvider/mod.scala](https://github.com/ScalablyTyped/Distribution/blob/2de3036843301f4e79930f6ddc9c580da6c92721/e/ethersproject__abstract-provider/src/main/scala/typings/ethersprojectAbstractProvider/mod.scala#L397)

**Comment by oyvindberg** [comment]
Sorry, I missed this.

The problem you're seeing here is that there isn't a way to specify vararg function types. That's what this thing tries to describe:
```scala
  @js.native
  trait Listener extends StObject {
    
    def apply(args: Any*): Unit = js.native
  }
  ```
So you're supposed to return a function which doesn't return anything.
To make this work you need to create a [js.Function](https://www.scala-js.org/doc/interoperability/types.html) with your wanted number of parameters, and cast it to `Listener`

I'll keep the issue open as a reminder to output some comment on types like `Listener` to explain this.

**Comment by web3rakko** [comment]
Thank you, and I understand what type of variable I should return.
