### ISSUE TITLE
use precompiled compiler-bridge for 2.13.12+

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#565]
See https://github.com/sbt/sbt/issues/7382

**Comment by oyvindberg** [comment]
Can probably be fixed here https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/Versions.scala#L36-L39

**Comment by mariussoutier** [comment]
Can you do a release quickly? This issue is blocking us.

**Comment by oyvindberg** [comment]
Yeah, give it a day or two 👍
