### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by cornerman** [ScalablyTyped/Converter#600]
Thank you so much for this library. Would you mind making a new release?

I just stumbled  upon this issue: https://github.com/ScalablyTyped/Converter/issues/583. It works with a snapshot, but having a release would be great. I think, there are a few other goodies on master that would be great to have as well.

Let me know if something is blocking a release and whether I can help with something.

**Comment by oyvindberg** [comment]
Released beta44 now 🥳
