### ISSUE TITLE
Research on how to work with complex type aliases

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#67]
For now we have pretty good support for working with `@ScalaJSDefined` traits, with the companion objects we generate.

A lot of type aliases have a shape like this `type T = A & (B | C)`. These are terrible to produce and to consume. I'm not sure about how to solve consuming (though we could generate a trait with a bunch of optional members), but we can certainly generate a companion object with many `apply` methods corresponding to all the shapes the object can have.

**Comment by adamsar** [comment]
I'm curious is the change to scala 3 fixes some of this stuff?

**Comment by oyvindberg** [comment]
@adamsar maybe some of it. The issue itself is for combinations of union and intersection types, which is syntactically very hard to work with. 

All generated objects now receive a `combineWith` combinator which should help a bit, but i think there is still scope for generating better boilerplate to deal with this. Probably in the form of a multi-step builder pattern
