### ISSUE TITLE
Fix failing libraries

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#68]
Look in the [failures](https://github.com/oyvindberg/ScalablyTyped/tree/master/failures) folder. Pick a library, and investigate causes of failure.

**Comment by rossoha** [comment]
@oyvindberg  Is it still relevant? (cause link to failures folder is broken)

**Comment by oyvindberg** [comment]
It is @rossoha , there are still a bunch of libraries which fail conversion. Note that this is no longer the easy beginner-task it was when I created it as all the low-hanging fruits are taken by now.

The current list of known failing libraries can be found in the commit messages from the distribution, for instance here https://github.com/ScalablyTyped/Distribution/commit/79c4184ccd1276ea11feb8807ae4bbac589a79b3 . I removed the failure logs themselves because they could be several 

If you need a library that doesn't currently work, or if you just want to try to fix one run it by me first so I can give some pointers and estimate how hard it is :)
